#!/usr/bin/env python3
"""gen_ciphers.py — 生成 cipher_data.h（mock.c 的密文与密钥常量）。

复刻 libmetasec_ml.so 的真实字符串加密方案。真 .so 的算法不是猜的，
是对 5 个真实解密函数做黑盒选择明文提炼得到的
（见 ../metasec_350101/extract_algo.py），并用 2,354 对真实
密文/明文交叉验证 100% 吻合：

    每个变体 = 周期 8 的 XOR 密钥流:   out[i] = in[i] ^ K[i % 8]
    v1 (0x12B904): K = a5 10 71 c7 50 90 e1 b1
    v2 (0x12BFA8): K = a5 12 81 d7 60 10 71 b2
    v3 (0x12C648): K = b5 20 91 e7 40 a0 e3 b6
    v4 (0x12C9A4): K = a7 50 78 c9 60 97 ef f1
    v5 (0x12CF90): K = 35 1f 7f f7 90 9f e1 b1

每个字符串有三种装载形态（真 .so 同样混合使用）：
  IMM  —— 立即数展开：密文以 mov/strb 立即数直接写进栈缓冲，
           .rodata 里完全没有密文痕迹（真 .so 用于短字符串）；
  RODATA —— 密文字节数组放 .rodata，调用点用拷贝循环搬进栈缓冲
           （真 .so 用于长字符串，ldr q0/d0 整块搬运）。

加密是解密函数族的严格逆运算，因此运行时 dec_vN 输出必然还原明文。
"""

# ---- 真实提取的 5 组周期-8 密钥流（勿改，与真 .so 一致）----
KEYS = {
    1: bytes.fromhex("a51071c75090e1b1"),
    2: bytes.fromhex("a51281d7601071b2"),
    3: bytes.fromhex("b52091e740a0e3b6"),
    4: bytes.fromhex("a75078c96097eff1"),
    5: bytes.fromhex("351f7ff7909fe1b1"),
}

# ---- 字符串清单: 名称 -> (变体, 明文, 装载形态) ----
STRINGS = {
    # JNI 注册数据
    "class":  (4, "com/mock/Mock", "RODATA"),
    "m0name": (1, "a", "IMM"),                      # 短串 -> 立即数展开
    "m0sig":  (2, "(IIJLjava/lang/String;Ljava/lang/Object;)Ljava/lang/Object;", "RODATA"),
    "m1name": (3, "b", "IMM"),                      # 短串 -> 立即数展开
    "m1sig":  (5, "()Ljava/lang/String;", "RODATA"),
    # 装饰字符串（metasec 风格：检测指纹 / 配置）
    "dbg1":   (1, "/data/adb/magisk", "RODATA"),
    "dbg2":   (2, "ro.debuggable", "RODATA"),
    "ver":    (3, "mock_sdk_v1.0", "RODATA"),
    "hello":  (4, "hello from mock native", "RODATA"),
    "tag":    (5, "MockSdk", "IMM"),
    # 反调试层（机制 7）：/proc 路径与 TracerPid 字段名同样走加密，
    # 否则 strings 一条命令就暴露检测点位置（真 .so 的检测特征串
    # 也全部加密存放，见 init_array ctor[68/69/86] 的预解密库）
    "procstatus": (2, "/proc/self/status", "RODATA"),
    "tracerpid":  (3, "TracerPid:", "IMM"),
}

def enc(v, s):
    """加密 = dec_vN 的逆运算: ct[i] = pt[i] ^ K[i%8]（XOR 自逆）。"""
    K = KEYS[v]
    return bytes(b ^ K[i % 8] for i, b in enumerate(s.encode()))

out = [
    "/* auto-generated by gen_ciphers.py — do not edit */",
    "/* scheme: libmetasec_ml.so 真实方案 = 周期-8 XOR 密钥流 x 5 变体 */",
    "",
]

# 5 组密钥常量 -> .rodata（真 .so 的密钥也由常量构成）
for v, K in KEYS.items():
    out.append(f"static const unsigned char K{v}[8] = {{")
    out.append("    " + ", ".join(f"0x{x:02x}" for x in K))
    out.append("};")
out.append("")

for name, (v, s, mode) in STRINGS.items():
    c = enc(v, s)
    if mode == "RODATA":
        # 密文数组进 .rodata，调用点 load_ct() 循环拷贝
        out.append(f"static const unsigned char C_{name}[{len(c)}] = {{")
        out.append("    " + ", ".join(f"0x{x:02x}" for x in c))
        out.append("};")
    else:
        # 立即数展开宏：编译后密文只以 mov/strb 立即数形式存在于 .text
        stores = "; ".join(f"b[{i}] = 0x{x:02x}" for i, x in enumerate(c))
        out.append(f"#define LOAD_C_{name}(b) do {{ {stores}; }} while (0)")
    out.append(f"#define L_{name} {len(c)}")
    out.append(f"#define V_{name} {v}")
    out.append("")

open("cipher_data.h", "w").write("\n".join(out))
print(f"cipher_data.h: {len(STRINGS)} strings "
      f"({sum(1 for _,_,m in STRINGS.values() if m=='IMM')} IMM / "
      f"{sum(1 for _,_,m in STRINGS.values() if m=='RODATA')} RODATA)")

# 自检：每条密文经对应变体解密后必须还原明文
for name, (v, s, mode) in STRINGS.items():
    dec = bytes(b ^ KEYS[v][i % 8] for i, b in enumerate(enc(v, s)))
    assert dec.decode() == s, name
print("self-test: all round-trips OK")
